# Generated by Django 6.0.4 on 2026-04-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('href', models.CharField(max_length=500)),
                ('image', models.URLField(blank=True, null=True)),
                ('type', models.CharField(choices=[('press-release', 'Press Release'), ('press-mention', 'Press Mention'), ('post', 'Post')], max_length=20)),
                ('type_prefix', models.CharField(blank=True, max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('published', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
