# Generated by Django 6.0.4 on 2026-04-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_newsarticle_href_newsarticle_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='news/'),
        ),
    ]
